import { createClient } from '@supabase/supabase-js'

// Dados dos membros analistas
const membros = [
  {
    nome: 'Ajax Perez Salvador',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo - Pinheiros',
    estado: 'SP',
    telefone: '(11) 99136-5956',
    email: 'apersal@uol.com.br',
  },
  {
    nome: 'Alessandra Brizotti Mazzieri',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '11 97634-6426',
    email: 'alessandra.mazzieri@uol.com.br',
  },
  {
    nome: 'Ana Paula Maluf',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    telefone: '(11) 94123-0102',
    email: 'anapaulazm@yahoo.com.br',
  },
  {
    nome: 'Ana Paula Pessanha Lima',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '11 93225-7575',
    email: 'anaplima@gmail.com',
  },
  {
    nome: 'André Orioli',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '(21) 99978-3477',
    email: 'profunda.psi@gmail.com',
  },
  {
    nome: 'Andréia Guiotti de Gregório',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Pires do Rio',
    estado: 'GO',
    telefone: '62 98137-3600',
    email: 'guiotti.andreia10@gmail.com',
  },
  {
    nome: 'Bárbara Pessanha Lima',
    tipo: 'Analista Didata em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '(21) 98266-8835',
    email: 'barbarapesslima@gmail.com',
    descricao: 'Clínica Revigore Rua República do Peru, 444. Copacabana.',
  },
  {
    nome: 'Beatriz Proença Whitaker de Assumpção',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 98134-4004',
    email: 'biapwa@gmail.com',
  },
  {
    nome: 'Carolina Held dos Santos',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99550-3540',
    email: 'carolinaheld17@gmail.com',
  },
  {
    nome: 'Caroline Santos Costa',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Porto Alegre',
    estado: 'RS',
    telefone: '(61) 98526-4506',
    email: 'caroline.s.costa82@gmail.com',
  },
  {
    nome: 'Claci Maria Strieder',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'Brasília',
    estado: 'DF',
    telefone: '(61) 99951-0003',
    email: 'clacims@gmail.com',
    descricao: 'SDN - Conj. Nacional de Brasília Torre Vermelha - Sala 4076',
  },
  {
    nome: 'Clarisse Grand Court',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '(21) 99182-7547',
    email: 'clarisse.court@gmail.com',
    descricao: 'Travessa Visconde de Morais, 226 - Botafogo',
  },
  {
    nome: 'Cristiane dos Santos',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99488-7593',
    email: 'crissantos68@gmail.com',
  },
  {
    nome: 'Daniel Gomes',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 98415-3021',
    email: 'dgterapia@gmail.com',
    descricao: 'Rua Doutor Thirso Martins, 100 cj 314 - Vila Mariana',
  },
  {
    nome: 'Daniela Aimar Euzebio',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99623-5529',
    email: 'daniela.euzebio@gmail.com',
    descricao: 'R. Domingos de Morais, 2781 (ao lado do metrô Santa Cruz)',
  },
  {
    nome: 'Denise Largman',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 94650-4444',
    email: 'deniselargman@gmail.com',
  },
  {
    nome: 'Dimas Künsch',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99789-1771',
    email: 'dimas.kunsch@gmail.com',
    descricao: 'R. Olimpia de Almeida Prado, 27 Barra Funda (próximo ao metrô Marechal Deodoro)',
  },
  {
    nome: 'Dulce Kurauti',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 95681-6931',
    email: 'dulce_kurauti@hotmail.com',
    descricao: 'Vila Mariana',
  },
  {
    nome: 'Elaine Cristina Bedin',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 2769-6475',
    email: 'elainebedinreis@gmail.com',
    descricao: 'Av. Santa Inês 909 sala 6 – Santana (próximo ao metro Santana e Jardins)',
  },
  {
    nome: 'Elfriede Cristina Seidel Walzberg',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Vinhedo',
    estado: 'SP',
    telefone: '(19) 99712-5072',
    email: 'elfriede.walzberg@gmail.com',
    descricao: 'Alameda Jabuta 616',
  },
  {
    nome: 'Euflausina Goes dos Santos',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 97140-3129',
    email: 'euflau@gmail.com',
    descricao: 'Rua Dr. Pinto Ferraz, 313 - casa 03 Vila Mariana',
  },
  {
    nome: 'Everton de Brito Dias',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(786) 2230125',
    email: 'everton.dias@gmail.com',
  },
  {
    nome: 'Gabriel Andrade',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Brasília',
    estado: 'DF',
    telefone: '(61) 99645-5430',
    email: 'gabriel.g3p@gmail.com',
  },
  {
    nome: 'Gabriel Yamaya',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '11 97181-2147',
    email: 'yamayag@gmail.com',
  },
  {
    nome: 'Gilmara Marques Fadim Alves',
    tipo: 'Analista Didata em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99201-0118',
    email: 'gmf.alves@terra.com.br',
    descricao: 'R. Manuel da Nóbrega, 354 - Paraíso (próximo ao Metrô Brigadeiro)',
  },
  {
    nome: 'Guilherme Henrique Gazzotto Duque',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Maringá',
    estado: 'PR',
    telefone: '(43) 99644-2171',
    email: 'guilherme.hg.duque@gmail.com',
  },
  {
    nome: 'Isa Fernanda Vianna Carvalho',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Guapimirim',
    estado: 'RJ',
    telefone: '(21) 2010-3363',
    email: 'isafvc@gmail.com',
    descricao: 'Atendimentos na Tijuca e no Catete no Rio de Janeiro.',
  },
  {
    nome: 'Itala Resende Carvalhal',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '(21) 99347-1835',
    email: 'itala.carvalhal@gmail.com',
  },
  {
    nome: 'Ivone Ferreira',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 5031-6203',
    email: 'ivone@nucleoivoneferreira.com.br',
    descricao: 'Rua Barão do Triunfo, 427 cj 1002 - Campo Belo',
  },
  {
    nome: 'Jaqueline Aguiar Carvalho',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Uberaba',
    estado: 'MG',
    telefone: '(34) 99117-6533',
    email: 'jac.aguiarcarvalho@gmail.com',
  },
  {
    nome: 'João Herck Costa Lima',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Florianópolis',
    estado: 'SC',
    telefone: '48 98446-6321',
    email: 'joaoherck@gmail.com',
  },
  {
    nome: 'José Eugenio de Oliveira Menezes',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99449-3332',
    email: 'menezes.eugenio@gmail.com',
    descricao: 'Rua Rocha 490. Apto 45',
  },
  {
    nome: 'José Lucivaldo Carvalho Silveira',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Aracaju',
    estado: 'SE',
    telefone: '79 99640-3723',
    email: 'ninokarva@hotmail.com',
  },
  {
    nome: 'José Luiz Balestrini Junior',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 982077766',
    email: 'balestrini@lungfu.com.br',
    descricao: 'Av. Ibijau, 236 - Moema',
  },
  {
    nome: 'Karla Angelica Alves de Paula',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Brasília',
    estado: 'DF',
    telefone: '61 99219-6754',
    email: 'karla.nova.2016@gmail.com',
  },
  {
    nome: 'Keller Alves Villela Ocaña Bruno',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo e Guarulhos',
    estado: 'SP',
    telefone: '(11) 982254490',
    email: 'kellervillela@terra.com.br',
    descricao: 'Rua Dr. Pinto Ferraz, 313 casa 3, Vila Mariana',
  },
  {
    nome: 'Laiana Graciela Nascimento Neves Soares',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Brasília',
    estado: 'DF',
    telefone: '61 98633-5848',
    email: 'laygnneves@gmail.com',
  },
  {
    nome: 'Leandro Scapellato Cruz',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Brasília',
    estado: 'DF',
    telefone: '(61) 99915-0219',
    email: 'institutoinnsaei@gmail.com',
    descricao: 'Instituto Innsaei, SHIN QL 5, CJ 05, Casa 12, Lago Norte',
  },
  {
    nome: 'Leila Cristina Montanha',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 98596-8335',
    email: 'leilacm@uol.com.br',
    descricao: 'Rua Ponte Alta, 36 - Aclimação',
  },
  {
    nome: 'Leonardo Lopes de Lima Salek',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '21 99148-1579',
    email: 'salekyoga@gmail.com',
  },
  {
    nome: 'Leonardo Torres',
    tipo: 'Analista Didata em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(54) 99331-0389',
    email: 'leosouzatorres@gmail.com',
    descricao: 'Rua Dr. Pinto Ferraz, 313 casa 3, Vila Mariana',
  },
  {
    nome: 'Lia Romano',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 5579-5761',
    email: 'lia.romano@uol.com.br',
    descricao: 'Rua Dona Avelina, 346 - Vila Mariana',
  },
  {
    nome: 'Lilian Wurzba',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 5051-6891',
    email: 'laliwi@uol.com.br',
    descricao: 'Al. Iraé, 620, cj. 93 - Moema',
  },
  {
    nome: 'Lorena de Sousa Oliveira',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Brasilia',
    estado: 'DF',
    telefone: '(61) 99179-1880',
    email: 'olivslorena@gmail.com',
    descricao: 'Qs 31 Conjunto 4 Lote 1, Riacho Fundo II',
  },
  {
    nome: 'Luciana Gimenes Branco',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99985-2654',
    email: 'lubranco@embranco.etc.br',
  },
  {
    nome: 'Luiza de Oliveira Burger',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '21 99771-0705',
    email: 'burgerluiza@gmail.com',
  },
  {
    nome: 'Marcella Helena Ferreira',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99604-5099',
    email: 'marcellahlferreira@gmail.com',
    descricao: 'Rua Doutor Thirso Martins, 100 cj 314 - Vila Mariana (metrô Santa Cruz)',
  },
  {
    nome: 'Maria Cristina Guarnieri',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo - Pinheiros',
    estado: 'SP',
    telefone: '(11) 3085-7973',
    email: 'crisguarnieri@uol.com.br',
  },
  {
    nome: 'Maria da Glória G. de Miranda',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99338-3545',
    email: 'mgloriagmiranda@gmail.com',
  },
  {
    nome: 'Maria Helena Soares Marinho',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 98256-5819',
    email: 'lemarinhofernandes@gmail.com',
  },
  {
    nome: 'Maria Ivanilde Ferreira Alves',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Brasília - Sobradinho',
    estado: 'DF',
    telefone: '(61) 99984-9922',
    email: 'ivyalves41@yahoo.com.br',
  },
  {
    nome: 'Marta Beatriz Conceição Guedes',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '(21) 99227-7468',
    email: 'guedes.marta@gmail.com',
  },
  {
    nome: 'Mauro Ângelo Soave Junior',
    tipo: 'Analista Didata em Formação',
    atendimento: 'Individual',
    cidade: 'Brasília',
    estado: 'DF',
    telefone: '(61) 99677 4719',
    email: 'maurosohan@gmail.com',
    descricao: 'Atendimento online',
  },
  {
    nome: 'Michella Paula Cechinel Reis',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Brasília',
    estado: 'DF',
    telefone: '(61) 99561-0990',
    email: 'michellacechinel@gmail.com',
    descricao: 'SHCGN 707, bloco A, casa 36, Asa Norte',
  },
  {
    nome: 'Mônica Araujo Contreras',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '21 99573-5043',
    email: 'psi.acontreras@gmail.com',
  },
  {
    nome: 'Monica Martinez',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99449-5034',
    email: 'monicamartinezpsi@gmail.com',
    descricao: 'Rua Girassol, 139 - cj. 42 - Vila Madalena',
  },
  {
    nome: 'Natalhe Vieni',
    tipo: 'Analista Didata em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99456-0194',
    email: 'natalhegarciacosta@gmail.com',
    descricao: 'Rua Doutor Pinto Ferraz, 313 casa 3 - Vila Mariana (ao lado do metrô vila mariana)',
  },
  {
    nome: 'Patricia Moura Vernalha',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '11 4098 5000',
    email: 'pmoura08@gmail.com',
    descricao: 'Rua Professor Germano Negrini ,113- Centro ,São Roque SP',
  },
  {
    nome: 'Patricia Silva Cordeiro',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Cotia',
    estado: 'SP',
    telefone: '(11) 981810985',
    email: 'patricia@pscergonomia.com.br',
    descricao: 'Alameda Bristol, 189',
  },
  {
    nome: 'Paula de Azevedo Bernardi Peñas',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 99604-6150',
    email: 'pab.paula.bernardi@gmail.com',
    descricao: 'R. Estevão de Almeida, 106 - Perdizes',
  },
  {
    nome: 'Pedro Pimentel Rocha',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Goiania',
    estado: 'GO',
    telefone: '62 99614-1018',
    email: 'pedrorocha2@gmail.com',
  },
  {
    nome: 'Pollyana Guilhermino de Pádua',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '11 97567-4855',
    email: 'ppadua@gmail.com',
  },
  {
    nome: 'Rafael Rodrigues de Souza',
    tipo: 'Analista Didata em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 997393491',
    email: 'rafael@solucaoativa.com.br',
    descricao: 'Rua Dr. Neto de Araújo, 320 – Sala 310 – Vila Mariana',
  },
  {
    nome: 'Renata Fraccini Pastorello',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '11 - 981673200',
    email: 'renatapastorello@hotmail.com',
  },
  {
    nome: 'Rita de Cássia Macieira',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 3842-5504',
    email: 'ritamacieira@bol.com.br',
    descricao: 'Rua dr. Alceu de Campos Rodrigues, 229 cj 512 - V. Olimpia',
  },
  {
    nome: 'Sebastien Pierre Maurice Baudry',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11 ) 97601-0125',
    email: 'oi@sebastianb.com',
    descricao: 'R. Manuel da Nóbrega, 354 – Paraíso / Rua Voluntários da pátria, 654 – Santana',
  },
  {
    nome: 'Selma de Fátima Silva Canôas',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo',
    estado: 'SP',
    telefone: '(11) 3032-4090',
    email: 'selmacanoas@gmail.com',
    descricao: 'Rua Ásia, 49 (400 metros do metro Sumaré)',
  },
  {
    nome: 'Silvana Gomes Venancio',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    telefone: '21 99799-2971',
    email: 'sgvenancio@gmail.com',
  },
  {
    nome: 'Silvia Maria Guerra Molina',
    tipo: 'Membro Analista',
    atendimento: 'Individual',
    cidade: 'São Paulo - Piracicaba',
    estado: 'SP',
    telefone: '(19) 99151-0909',
    email: 'silvia.maria@gmail.com',
  },
  {
    nome: 'Simone Magaldi',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo - Moema',
    estado: 'SP',
    telefone: '(11) 5535-4695',
    email: 'simonemagaldi@ijep.com.br',
  },
  {
    nome: 'Tania Pulier Garrido',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'São Vicente',
    estado: 'SP',
    telefone: '(13) 99722-9503',
    email: 'tania.pulier@gmail.com',
    descricao: 'Rua Pero Vaz de Caminha, 293, Vila Valença',
  },
  {
    nome: 'Veridiana Aleixo de Moura e Souza',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Bragança Paulista',
    estado: 'SP',
    telefone: '11 98384-7092',
    email: 'veridiana.aleixo@gmail.com',
  },
  {
    nome: 'Wagner Hilário Padula Borges',
    tipo: 'Analista em Formação',
    atendimento: 'Individual',
    cidade: 'Guarulhos',
    estado: 'SP',
    telefone: '11 99603-1980',
    email: 'wagner.hilariopb@gmail.com',
  },
  {
    nome: 'Waldemar Magaldi Filho',
    tipo: 'Analista Didata',
    atendimento: 'Individual',
    cidade: 'São Paulo - Moema',
    estado: 'SP',
    telefone: '(11) 5535-4695',
    email: 'wmagaldi@ijep.com.br',
  },
]

async function migrateMembros() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.SUPABASE_SERVICE_KEY

  if (!supabaseUrl || !supabaseKey) {
    console.error('❌ Erro: Variáveis de ambiente não configuradas')
    console.error('   Configure NEXT_PUBLIC_SUPABASE_URL e SUPABASE_SERVICE_KEY')
    process.exit(1)
  }

  const supabase = createClient(supabaseUrl, supabaseKey)

  console.log('🚀 Iniciando migração de membros analistas...\n')

  try {
    // Inserir membros
    const { data, error } = await supabase
      .from('membros_analistas')
      .insert(membros)
      .select()

    if (error) {
      console.error('❌ Erro ao inserir membros:', error.message)
      process.exit(1)
    }

    console.log(`✅ ${data?.length || 0} membros analistas migrados com sucesso!`)
    console.log('\n📊 Resumo:')

    // Contar por tipo
    const tipos = membros.reduce((acc, m) => {
      acc[m.tipo] = (acc[m.tipo] || 0) + 1
      return acc
    }, {} as Record<string, number>)

    Object.entries(tipos).forEach(([tipo, count]) => {
      console.log(`   - ${tipo}: ${count}`)
    })

    console.log('\n✨ Migração concluída!')
  } catch (err) {
    console.error('❌ Erro durante a migração:', err)
    process.exit(1)
  }
}

migrateMembros()
